# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Deep Learning Frameworks</font>

# Keras - Introdução

In [1]:
# Instalando keras
!pip install keras

In [2]:
import keras
print (keras.__version__)

Using TensorFlow backend.


2.3.1


In [3]:
import tensorflow
print (tensorflow.__version__)

2.1.0


## Carregando os Dados

Vamos criar um modelo de classificação de vinhos! Dataset utilizado:
    
http://mlr.cs.umass.edu/ml/datasets.html

Obs: O dataset está disponível junto com este jupyter notebook.

In [4]:
#!wget http://mlr.cs.umass.edu/ml/machine-learning-databases/wine/wine.data

In [5]:
# Importando pacotes fundamentais
import pandas
import numpy as np
from keras.utils import np_utils

In [6]:
# Como o dataset não possui header, vamos incluir
dados = pandas.read_csv("wine.data.txt", names=["Class","Alcohol","Malic Alic","Ash","Alcanility of Ash","Magnesium",
                    "Total phenols","Flavanoids","Nonflavanoid phenols","Proanthocyanins","Color intensity","Hue","OD280_OD315_diluted wines",
                    "Proline"])

In [7]:
# Obtendo os valores de classe e armazenando em y
y = dados["Class"].values

In [8]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


In [9]:
# Ajustando o formato de y
# Converte array 1-D em matriz 
y_train = np_utils.to_categorical(y)

In [10]:
print(y_train)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1.

In [11]:
# Keras espera receber as classes em diferentes colunas. Como temos 3 classes, precisamos de 3 colunas.
y_train = y_train[:,1:4]

In [12]:
print(y_train)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [13]:
del(dados["Class"])
dados = dados.values

## Definindo a Arquitetura do Modelo

In [14]:
import keras

Em seguida, vamos importar o tipo de modelo Sequential do Keras. Isto é simplesmente uma pilha linear de camadas de rede neural, e é perfeito para o tipo de feed-forward CNN que estamos construindo.

In [15]:
from keras.models import Sequential

Em seguida, vamos importar as camadas "core" do Keras. Estas são as camadas que são usadas em quase qualquer rede neural.

In [16]:
from keras.layers import Dense, Dropout, Activation, Flatten

Agora importamos o otimizador, neste caso o SGD - Stochastic Gradient Descent

In [17]:
from keras.optimizers import SGD

Finalmente, vamos importar alguns utilitários. Isso nos ajudará a transformar nossos dados.

In [18]:
from keras.utils import np_utils

## Construindo as Camadas

In [19]:
model = Sequential()

Camadas totalmente conectadas são definidas usando a classe Dense. Podemos especificar o número de neurônios na camada como o primeiro argumento, o método de inicialização como o segundo argumento com kernel_initializer e especificar a função de ativação usando o argumento activation.

O valor 'normal' no parâmetro kernel_initializer gera pequenos valores randômicos com uma distirbuição Graussiana (normal).

Usaremos a função de ativação ReLu nas duas primeiras camadas e a função sigmóide na camada de saída. Costumava-se usar as funções da ativação sigmoid e tanh para todas as camadas. Mas atualmente, o melhor desempenho é alcançado usando a função de ativação ReLu. Usamos um sigmoide nas camadas internas para garantir que nossa saída de rede esteja entre 0 e 1 e e função softmax na camada de saída, comumente usada em problemas de classificação.

In [20]:
model.add(Dense(40, input_dim = 13, kernel_initializer = 'normal', activation = 'relu'))

In [21]:
model.add(Dense(10, kernel_initializer = 'normal', activation = "sigmoid"))

In [22]:
model.add(Dropout(0.10))

In [23]:
model.add(Dense(5, kernel_initializer = 'normal', activation = "sigmoid"))

In [24]:
model.add(Dense(3, kernel_initializer = 'normal', activation = "softmax"))

## Otimização com Stochastic Gradient Descent

Mais otimizadores em: https://keras.io/optimizers/

In [25]:
sgd = keras.optimizers.Adam(lr = 0.001, beta_1 = 0.9, beta_2 = 0.999, epsilon = 1e-08, decay = 0.0)

## Compilação do Modelo e Treinamento

In [26]:
model.compile(loss = 'categorical_crossentropy', optimizer = sgd,  metrics = ["acc"])

In [27]:
model.fit(dados, y_train, epochs = 1600, verbose = 1)

Epoch 1/1600
178/178 [==============================] - 0s 771us/step - loss: 1.0943 - acc: 0.3315
Epoch 2/1600
178/178 [==============================] - 0s 45us/step - loss: 1.0930 - acc: 0.4101
Epoch 3/1600
178/178 [==============================] - 0s 45us/step - loss: 1.0910 - acc: 0.3989
Epoch 4/1600
178/178 [==============================] - 0s 50us/step - loss: 1.0901 - acc: 0.3989
Epoch 5/1600
178/178 [==============================] - 0s 49us/step - loss: 1.0895 - acc: 0.3989
Epoch 6/1600
178/178 [==============================] - 0s 42us/step - loss: 1.0889 - acc: 0.3989
Epoch 7/1600
178/178 [==============================] - 0s 39us/step - loss: 1.0882 - acc: 0.3989
Epoch 8/1600
178/178 [==============================] - 0s 42us/step - loss: 1.0876 - acc: 0.3989
Epoch 9/1600
178/178 [==============================] - 0s 45us/step - loss: 1.0870 - acc: 0.3989
Epoch 10/1600
178/178 [==============================] - 0s 41us/step - loss: 1.0865 - acc: 0.3989
Epoch 11/1600
178/

178/178 [==============================] - 0s 35us/step - loss: 0.7958 - acc: 0.6629
Epoch 84/1600
178/178 [==============================] - 0s 35us/step - loss: 0.7633 - acc: 0.6685
Epoch 85/1600
178/178 [==============================] - 0s 31us/step - loss: 0.7682 - acc: 0.6685
Epoch 86/1600
178/178 [==============================] - 0s 39us/step - loss: 0.7732 - acc: 0.6742
Epoch 87/1600
178/178 [==============================] - 0s 34us/step - loss: 0.7587 - acc: 0.6798
Epoch 88/1600
178/178 [==============================] - 0s 39us/step - loss: 0.7569 - acc: 0.6798
Epoch 89/1600
178/178 [==============================] - 0s 31us/step - loss: 0.7397 - acc: 0.6854
Epoch 90/1600
178/178 [==============================] - 0s 36us/step - loss: 0.7569 - acc: 0.6685
Epoch 91/1600
178/178 [==============================] - 0s 32us/step - loss: 0.7425 - acc: 0.6742
Epoch 92/1600
178/178 [==============================] - 0s 35us/step - loss: 0.7688 - acc: 0.6685
Epoch 93/1600
178/178 [=

178/178 [==============================] - 0s 33us/step - loss: 0.5991 - acc: 0.6966
Epoch 166/1600
178/178 [==============================] - 0s 33us/step - loss: 0.5997 - acc: 0.6966
Epoch 167/1600
178/178 [==============================] - 0s 30us/step - loss: 0.6002 - acc: 0.6854
Epoch 168/1600
178/178 [==============================] - 0s 33us/step - loss: 0.5917 - acc: 0.6966
Epoch 169/1600
178/178 [==============================] - 0s 31us/step - loss: 0.6133 - acc: 0.6854
Epoch 170/1600
178/178 [==============================] - 0s 34us/step - loss: 0.5935 - acc: 0.6966
Epoch 171/1600
178/178 [==============================] - 0s 33us/step - loss: 0.5879 - acc: 0.6966
Epoch 172/1600
178/178 [==============================] - 0s 32us/step - loss: 0.5947 - acc: 0.7022
Epoch 173/1600
178/178 [==============================] - 0s 36us/step - loss: 0.5856 - acc: 0.7079
Epoch 174/1600
178/178 [==============================] - 0s 30us/step - loss: 0.5795 - acc: 0.7022
Epoch 175/1600


178/178 [==============================] - 0s 33us/step - loss: 0.5830 - acc: 0.6910
Epoch 248/1600
178/178 [==============================] - 0s 33us/step - loss: 0.5527 - acc: 0.7022
Epoch 249/1600
178/178 [==============================] - 0s 32us/step - loss: 0.5496 - acc: 0.7135
Epoch 250/1600
178/178 [==============================] - 0s 34us/step - loss: 0.5499 - acc: 0.7022
Epoch 251/1600
178/178 [==============================] - 0s 32us/step - loss: 0.5541 - acc: 0.7079
Epoch 252/1600
178/178 [==============================] - 0s 35us/step - loss: 0.5531 - acc: 0.7022
Epoch 253/1600
178/178 [==============================] - 0s 31us/step - loss: 0.5699 - acc: 0.6966
Epoch 254/1600
178/178 [==============================] - 0s 33us/step - loss: 0.5458 - acc: 0.7135
Epoch 255/1600
178/178 [==============================] - 0s 34us/step - loss: 0.5499 - acc: 0.7022
Epoch 256/1600
178/178 [==============================] - 0s 31us/step - loss: 0.5481 - acc: 0.7135
Epoch 257/1600


178/178 [==============================] - 0s 35us/step - loss: 0.5280 - acc: 0.7135
Epoch 330/1600
178/178 [==============================] - 0s 33us/step - loss: 0.5386 - acc: 0.7079
Epoch 331/1600
178/178 [==============================] - 0s 34us/step - loss: 0.5482 - acc: 0.7022
Epoch 332/1600
178/178 [==============================] - 0s 33us/step - loss: 0.5440 - acc: 0.6966
Epoch 333/1600
178/178 [==============================] - 0s 34us/step - loss: 0.5451 - acc: 0.7079
Epoch 334/1600
178/178 [==============================] - 0s 31us/step - loss: 0.5381 - acc: 0.7022
Epoch 335/1600
178/178 [==============================] - 0s 33us/step - loss: 0.5431 - acc: 0.7079
Epoch 336/1600
178/178 [==============================] - 0s 36us/step - loss: 0.5512 - acc: 0.6966
Epoch 337/1600
178/178 [==============================] - 0s 31us/step - loss: 0.5655 - acc: 0.7022
Epoch 338/1600
178/178 [==============================] - 0s 35us/step - loss: 0.5411 - acc: 0.7079
Epoch 339/1600


178/178 [==============================] - 0s 32us/step - loss: 0.5214 - acc: 0.7079
Epoch 412/1600
178/178 [==============================] - 0s 31us/step - loss: 0.5287 - acc: 0.7135
Epoch 413/1600
178/178 [==============================] - 0s 37us/step - loss: 0.5106 - acc: 0.7135
Epoch 414/1600
178/178 [==============================] - 0s 30us/step - loss: 0.5155 - acc: 0.7135
Epoch 415/1600
178/178 [==============================] - 0s 33us/step - loss: 0.5175 - acc: 0.7191
Epoch 416/1600
178/178 [==============================] - 0s 33us/step - loss: 0.5196 - acc: 0.7191
Epoch 417/1600
178/178 [==============================] - 0s 34us/step - loss: 0.5257 - acc: 0.7135
Epoch 418/1600
178/178 [==============================] - 0s 32us/step - loss: 0.5208 - acc: 0.7135
Epoch 419/1600
178/178 [==============================] - 0s 30us/step - loss: 0.5220 - acc: 0.7191
Epoch 420/1600
178/178 [==============================] - 0s 33us/step - loss: 0.5208 - acc: 0.7191
Epoch 421/1600


178/178 [==============================] - 0s 31us/step - loss: 0.5086 - acc: 0.7079
Epoch 494/1600
178/178 [==============================] - 0s 33us/step - loss: 0.5142 - acc: 0.7191
Epoch 495/1600
178/178 [==============================] - 0s 35us/step - loss: 0.4980 - acc: 0.7191
Epoch 496/1600
178/178 [==============================] - 0s 31us/step - loss: 0.5010 - acc: 0.7135
Epoch 497/1600
178/178 [==============================] - 0s 34us/step - loss: 0.5165 - acc: 0.7191
Epoch 498/1600
178/178 [==============================] - 0s 30us/step - loss: 0.5086 - acc: 0.7135
Epoch 499/1600
178/178 [==============================] - 0s 35us/step - loss: 0.5214 - acc: 0.7135
Epoch 500/1600
178/178 [==============================] - 0s 31us/step - loss: 0.5085 - acc: 0.7191
Epoch 501/1600
178/178 [==============================] - 0s 31us/step - loss: 0.5134 - acc: 0.7191
Epoch 502/1600
178/178 [==============================] - 0s 34us/step - loss: 0.5117 - acc: 0.7191
Epoch 503/1600


178/178 [==============================] - 0s 36us/step - loss: 0.5141 - acc: 0.7135
Epoch 576/1600
178/178 [==============================] - 0s 32us/step - loss: 0.5174 - acc: 0.7079
Epoch 577/1600
178/178 [==============================] - 0s 34us/step - loss: 0.5186 - acc: 0.7135
Epoch 578/1600
178/178 [==============================] - 0s 33us/step - loss: 0.4987 - acc: 0.7079
Epoch 579/1600
178/178 [==============================] - 0s 33us/step - loss: 0.5127 - acc: 0.7135
Epoch 580/1600
178/178 [==============================] - 0s 35us/step - loss: 0.5059 - acc: 0.7191
Epoch 581/1600
178/178 [==============================] - 0s 33us/step - loss: 0.5009 - acc: 0.7079
Epoch 582/1600
178/178 [==============================] - 0s 35us/step - loss: 0.5089 - acc: 0.7191
Epoch 583/1600
178/178 [==============================] - 0s 32us/step - loss: 0.5015 - acc: 0.7191
Epoch 584/1600
178/178 [==============================] - 0s 34us/step - loss: 0.5032 - acc: 0.7191
Epoch 585/1600


178/178 [==============================] - 0s 36us/step - loss: 0.3401 - acc: 0.9326
Epoch 658/1600
178/178 [==============================] - 0s 32us/step - loss: 0.3516 - acc: 0.9213
Epoch 659/1600
178/178 [==============================] - 0s 34us/step - loss: 0.3307 - acc: 0.9270
Epoch 660/1600
178/178 [==============================] - 0s 33us/step - loss: 0.3198 - acc: 0.9494
Epoch 661/1600
178/178 [==============================] - 0s 34us/step - loss: 0.3231 - acc: 0.9382
Epoch 662/1600
178/178 [==============================] - 0s 33us/step - loss: 0.3102 - acc: 0.9494
Epoch 663/1600
178/178 [==============================] - 0s 32us/step - loss: 0.3171 - acc: 0.9270
Epoch 664/1600
178/178 [==============================] - 0s 35us/step - loss: 0.3102 - acc: 0.9551
Epoch 665/1600
178/178 [==============================] - 0s 32us/step - loss: 0.3204 - acc: 0.9382
Epoch 666/1600
178/178 [==============================] - 0s 35us/step - loss: 0.3044 - acc: 0.9494
Epoch 667/1600


178/178 [==============================] - 0s 36us/step - loss: 0.1763 - acc: 0.9775
Epoch 740/1600
178/178 [==============================] - 0s 50us/step - loss: 0.1668 - acc: 0.9775
Epoch 741/1600
178/178 [==============================] - 0s 37us/step - loss: 0.1825 - acc: 0.9775
Epoch 742/1600
178/178 [==============================] - 0s 39us/step - loss: 0.1607 - acc: 0.9775
Epoch 743/1600
178/178 [==============================] - 0s 34us/step - loss: 0.1736 - acc: 0.9775
Epoch 744/1600
178/178 [==============================] - 0s 36us/step - loss: 0.1821 - acc: 0.9775
Epoch 745/1600
178/178 [==============================] - 0s 33us/step - loss: 0.1674 - acc: 0.9775
Epoch 746/1600
178/178 [==============================] - 0s 35us/step - loss: 0.1789 - acc: 0.9663
Epoch 747/1600
178/178 [==============================] - 0s 32us/step - loss: 0.1700 - acc: 0.9775
Epoch 748/1600
178/178 [==============================] - 0s 33us/step - loss: 0.1769 - acc: 0.9719
Epoch 749/1600


178/178 [==============================] - 0s 31us/step - loss: 0.1266 - acc: 0.9775
Epoch 822/1600
178/178 [==============================] - 0s 36us/step - loss: 0.1287 - acc: 0.9719
Epoch 823/1600
178/178 [==============================] - 0s 31us/step - loss: 0.1322 - acc: 0.9775
Epoch 824/1600
178/178 [==============================] - 0s 31us/step - loss: 0.1229 - acc: 0.9831
Epoch 825/1600
178/178 [==============================] - 0s 32us/step - loss: 0.1296 - acc: 0.9831
Epoch 826/1600
178/178 [==============================] - 0s 31us/step - loss: 0.1402 - acc: 0.9775
Epoch 827/1600
178/178 [==============================] - 0s 35us/step - loss: 0.1573 - acc: 0.9663
Epoch 828/1600
178/178 [==============================] - 0s 31us/step - loss: 0.1981 - acc: 0.9551
Epoch 829/1600
178/178 [==============================] - 0s 33us/step - loss: 0.1464 - acc: 0.9663
Epoch 830/1600
178/178 [==============================] - 0s 32us/step - loss: 0.1617 - acc: 0.9551
Epoch 831/1600


178/178 [==============================] - 0s 32us/step - loss: 0.1273 - acc: 0.9775
Epoch 904/1600
178/178 [==============================] - 0s 33us/step - loss: 0.1204 - acc: 0.9719
Epoch 905/1600
178/178 [==============================] - 0s 31us/step - loss: 0.1260 - acc: 0.9775
Epoch 906/1600
178/178 [==============================] - 0s 35us/step - loss: 0.1302 - acc: 0.9719
Epoch 907/1600
178/178 [==============================] - 0s 32us/step - loss: 0.1403 - acc: 0.9663
Epoch 908/1600
178/178 [==============================] - 0s 36us/step - loss: 0.1498 - acc: 0.9663
Epoch 909/1600
178/178 [==============================] - 0s 30us/step - loss: 0.1250 - acc: 0.9775
Epoch 910/1600
178/178 [==============================] - 0s 30us/step - loss: 0.1365 - acc: 0.9663
Epoch 911/1600
178/178 [==============================] - 0s 35us/step - loss: 0.1221 - acc: 0.9775
Epoch 912/1600
178/178 [==============================] - 0s 31us/step - loss: 0.1292 - acc: 0.9719
Epoch 913/1600


178/178 [==============================] - 0s 34us/step - loss: 0.0922 - acc: 0.9888
Epoch 986/1600
178/178 [==============================] - 0s 32us/step - loss: 0.1230 - acc: 0.9719
Epoch 987/1600
178/178 [==============================] - 0s 30us/step - loss: 0.0979 - acc: 0.9831
Epoch 988/1600
178/178 [==============================] - 0s 35us/step - loss: 0.1253 - acc: 0.9663
Epoch 989/1600
178/178 [==============================] - 0s 31us/step - loss: 0.0967 - acc: 0.9831
Epoch 990/1600
178/178 [==============================] - 0s 37us/step - loss: 0.0923 - acc: 0.9831
Epoch 991/1600
178/178 [==============================] - 0s 33us/step - loss: 0.1006 - acc: 0.9775
Epoch 992/1600
178/178 [==============================] - 0s 33us/step - loss: 0.1522 - acc: 0.9551
Epoch 993/1600
178/178 [==============================] - 0s 32us/step - loss: 0.1209 - acc: 0.9719
Epoch 994/1600
178/178 [==============================] - 0s 30us/step - loss: 0.1718 - acc: 0.9551
Epoch 995/1600


178/178 [==============================] - 0s 31us/step - loss: 0.0850 - acc: 0.9888
Epoch 1067/1600
178/178 [==============================] - 0s 38us/step - loss: 0.0864 - acc: 0.9888
Epoch 1068/1600
178/178 [==============================] - 0s 33us/step - loss: 0.0994 - acc: 0.9831
Epoch 1069/1600
178/178 [==============================] - 0s 34us/step - loss: 0.0839 - acc: 0.9888
Epoch 1070/1600
178/178 [==============================] - 0s 33us/step - loss: 0.1257 - acc: 0.9719
Epoch 1071/1600
178/178 [==============================] - 0s 34us/step - loss: 0.0957 - acc: 0.9775
Epoch 1072/1600
178/178 [==============================] - 0s 33us/step - loss: 0.1718 - acc: 0.9663
Epoch 1073/1600
178/178 [==============================] - 0s 31us/step - loss: 0.1634 - acc: 0.9494
Epoch 1074/1600
178/178 [==============================] - 0s 35us/step - loss: 0.1798 - acc: 0.9382
Epoch 1075/1600
178/178 [==============================] - 0s 31us/step - loss: 0.1282 - acc: 0.9663
Epoch 

178/178 [==============================] - 0s 30us/step - loss: 0.0774 - acc: 0.9888
Epoch 1148/1600
178/178 [==============================] - 0s 33us/step - loss: 0.0922 - acc: 0.9831
Epoch 1149/1600
178/178 [==============================] - 0s 32us/step - loss: 0.0747 - acc: 0.9888
Epoch 1150/1600
178/178 [==============================] - 0s 31us/step - loss: 0.0917 - acc: 0.9831
Epoch 1151/1600
178/178 [==============================] - 0s 34us/step - loss: 0.0892 - acc: 0.9831
Epoch 1152/1600
178/178 [==============================] - 0s 30us/step - loss: 0.0711 - acc: 0.9888
Epoch 1153/1600
178/178 [==============================] - 0s 35us/step - loss: 0.0764 - acc: 0.9888
Epoch 1154/1600
178/178 [==============================] - 0s 31us/step - loss: 0.0873 - acc: 0.9831
Epoch 1155/1600
178/178 [==============================] - 0s 33us/step - loss: 0.0925 - acc: 0.9831
Epoch 1156/1600
178/178 [==============================] - 0s 32us/step - loss: 0.0790 - acc: 0.9831
Epoch 

178/178 [==============================] - 0s 32us/step - loss: 0.0888 - acc: 0.9831
Epoch 1229/1600
178/178 [==============================] - 0s 34us/step - loss: 0.0689 - acc: 0.9888
Epoch 1230/1600
178/178 [==============================] - 0s 34us/step - loss: 0.0861 - acc: 0.9831
Epoch 1231/1600
178/178 [==============================] - 0s 31us/step - loss: 0.0722 - acc: 0.9888
Epoch 1232/1600
178/178 [==============================] - 0s 36us/step - loss: 0.0950 - acc: 0.9775
Epoch 1233/1600
178/178 [==============================] - 0s 32us/step - loss: 0.0893 - acc: 0.9831
Epoch 1234/1600
178/178 [==============================] - 0s 33us/step - loss: 0.0805 - acc: 0.9888
Epoch 1235/1600
178/178 [==============================] - 0s 33us/step - loss: 0.0695 - acc: 0.9888
Epoch 1236/1600
178/178 [==============================] - 0s 30us/step - loss: 0.0791 - acc: 0.9831
Epoch 1237/1600
178/178 [==============================] - 0s 33us/step - loss: 0.0927 - acc: 0.9831
Epoch 

178/178 [==============================] - 0s 36us/step - loss: 0.0717 - acc: 0.9888
Epoch 1310/1600
178/178 [==============================] - 0s 36us/step - loss: 0.1162 - acc: 0.9719
Epoch 1311/1600
178/178 [==============================] - 0s 35us/step - loss: 0.0754 - acc: 0.9888
Epoch 1312/1600
178/178 [==============================] - 0s 34us/step - loss: 0.0689 - acc: 0.9888
Epoch 1313/1600
178/178 [==============================] - 0s 36us/step - loss: 0.0704 - acc: 0.9888
Epoch 1314/1600
178/178 [==============================] - 0s 33us/step - loss: 0.0665 - acc: 0.9888
Epoch 1315/1600
178/178 [==============================] - 0s 37us/step - loss: 0.0675 - acc: 0.9888
Epoch 1316/1600
178/178 [==============================] - 0s 33us/step - loss: 0.0683 - acc: 0.9888
Epoch 1317/1600
178/178 [==============================] - 0s 36us/step - loss: 0.0676 - acc: 0.9888
Epoch 1318/1600
178/178 [==============================] - 0s 33us/step - loss: 0.0825 - acc: 0.9831
Epoch 

178/178 [==============================] - 0s 30us/step - loss: 0.0675 - acc: 0.9888
Epoch 1391/1600
178/178 [==============================] - 0s 35us/step - loss: 0.0759 - acc: 0.9831
Epoch 1392/1600
178/178 [==============================] - 0s 31us/step - loss: 0.0720 - acc: 0.9831
Epoch 1393/1600
178/178 [==============================] - 0s 35us/step - loss: 0.0688 - acc: 0.9888
Epoch 1394/1600
178/178 [==============================] - 0s 35us/step - loss: 0.0953 - acc: 0.9775
Epoch 1395/1600
178/178 [==============================] - 0s 34us/step - loss: 0.0672 - acc: 0.9888
Epoch 1396/1600
178/178 [==============================] - 0s 33us/step - loss: 0.0901 - acc: 0.9831
Epoch 1397/1600
178/178 [==============================] - 0s 32us/step - loss: 0.0706 - acc: 0.9888
Epoch 1398/1600
178/178 [==============================] - 0s 36us/step - loss: 0.1043 - acc: 0.9775
Epoch 1399/1600
178/178 [==============================] - 0s 32us/step - loss: 0.0661 - acc: 0.9888
Epoch 

178/178 [==============================] - 0s 34us/step - loss: 0.0628 - acc: 0.9888
Epoch 1472/1600
178/178 [==============================] - 0s 32us/step - loss: 0.0804 - acc: 0.9831
Epoch 1473/1600
178/178 [==============================] - 0s 37us/step - loss: 0.0818 - acc: 0.9831
Epoch 1474/1600
178/178 [==============================] - 0s 41us/step - loss: 0.1005 - acc: 0.9775
Epoch 1475/1600
178/178 [==============================] - 0s 32us/step - loss: 0.0672 - acc: 0.9888
Epoch 1476/1600
178/178 [==============================] - 0s 36us/step - loss: 0.0640 - acc: 0.9888
Epoch 1477/1600
178/178 [==============================] - 0s 35us/step - loss: 0.0735 - acc: 0.9831
Epoch 1478/1600
178/178 [==============================] - 0s 33us/step - loss: 0.0786 - acc: 0.9831
Epoch 1479/1600
178/178 [==============================] - 0s 35us/step - loss: 0.0708 - acc: 0.9888
Epoch 1480/1600
178/178 [==============================] - 0s 33us/step - loss: 0.0851 - acc: 0.9775
Epoch 

178/178 [==============================] - 0s 33us/step - loss: 0.0634 - acc: 0.9888
Epoch 1553/1600
178/178 [==============================] - 0s 35us/step - loss: 0.0831 - acc: 0.9831
Epoch 1554/1600
178/178 [==============================] - 0s 33us/step - loss: 0.0571 - acc: 0.9888
Epoch 1555/1600
178/178 [==============================] - 0s 32us/step - loss: 0.0794 - acc: 0.9831
Epoch 1556/1600
178/178 [==============================] - 0s 33us/step - loss: 0.0620 - acc: 0.9831
Epoch 1557/1600
178/178 [==============================] - 0s 31us/step - loss: 0.0641 - acc: 0.9888
Epoch 1558/1600
178/178 [==============================] - 0s 34us/step - loss: 0.0801 - acc: 0.9831
Epoch 1559/1600
178/178 [==============================] - 0s 32us/step - loss: 0.0746 - acc: 0.9831
Epoch 1560/1600
178/178 [==============================] - 0s 35us/step - loss: 0.1021 - acc: 0.9775
Epoch 1561/1600
178/178 [==============================] - 0s 34us/step - loss: 0.1518 - acc: 0.9663
Epoch 

In [28]:
score = model.evaluate(dados, y_train, verbose = 0)

In [29]:
print(score)

[0.07268329052610344, 0.9719101190567017]


## Fim